#!/bin/sh

# Wrapper for invoking the Python softIoc.  This IOC needs to be called with a
# complete path and with PYTHONPATH set up correctly.  It's easier to
# configure this here in shell script than in the program itself!

HERE="$(readlink -fn "$(dirname "$0")")"

[ -n "$PYTHONPATH" ]  &&  PYTHONPATH="$PYTHONPATH:"
export PYTHONPATH="$PYTHONPATH""$HERE/python"

"$HERE/bin/linux-x86/softIoc" "$@"
