#!/bin/sh

# Wrapper for invoking the Python softIoc.  This IOC needs to be called with a
# complete path and with PYTHONPATH set up correctly.  It's easier to
# configure this here in shell script than in the program itself!

export HERE="$(readlink -fn "$(dirname "$0")")"
export PYTHONPATH="$PYTHONPATH${PYTHONPATH:+:}$HERE/python"

exec "$HERE/bin/linux-x86/softIoc" "$@"
